RegisterServerEvent('procon:server:esx')
AddEventHandler('procon:server:esx', function(cb)
	cb(ESX)
end)

RegisterServerEvent('procon:server:xPlayer')
AddEventHandler('procon:server:xPlayer', function(src, cb)
	local xPlayer = ESX.GetPlayerFromId(src)
	cb(xPlayer)
end)

RegisterServerEvent('procon:server:qbxPlayer')
AddEventHandler('procon:server:qbxPlayer', function(src, cb)
	local qbxplayer = exports.qbx_core:GetPlayer(src)
	cb(qbxplayer)
end)